SELECT
    F.SALES_KEY,
    F.ORDER_KEY,
    O.ORDER_ID,
    
    D.DATE_KEY,
    D.FULL_DATE,
    D.DAY_NUMBER,
    D.MONTH_NUMBER,
    D.MONTH_NAME,
    D.QUARTER_NUMBER,
    D.YEAR_NUMBER,
    
    R.RESTAURANT_KEY,
    R.RESTAURANT_ID,
    R.RESTAURANT_NAME,
    R.SUBZONE,
    R.CITY,
    
    F.BILL_SUBTOTAL,
    F.PACKAGING_CHARGES,
    F.RESTAURANT_DISCOUNT_PROMO,
    F.RESTAURANT_DISCOUNT_FLAT_OFF,
    F.GOLD_DISCOUNT,
    F.BRAND_PACK_DISCOUNT,
    F.TOTAL_AMOUNT,
    F.DISTANCE_KM,
    
    COALESCE(F.RESTAURANT_DISCOUNT_PROMO, 0)
    + COALESCE(F.RESTAURANT_DISCOUNT_FLAT_OFF, 0)
    + COALESCE(F.GOLD_DISCOUNT, 0)
    + COALESCE(F.BRAND_PACK_DISCOUNT, 0)
    AS TOTAL_DISCOUNT
    
FROM GOLD_LAYER.FACT_SALES F

LEFT JOIN GOLD_LAYER.DIM_ORDERS O
    ON F.ORDER_KEY = O.ORDER_KEY

LEFT JOIN GOLD_LAYER.DIM_RESTAURANTS R
    ON F.RESTRAUNT_KEY = R.RESTAURANT_KEY

LEFT JOIN GOLD_LAYER.DIM_DATE D
    ON TO_DATE(O.ORDER_PLACED_AT) = D.FULL_DATE;