
MERGE INTO DATA_MART.DIM_CUSTOMER T
USING
(
    SELECT
        HC.CUSTOMER_ID,
        SCD.CUSTOMER_NAME,
        SCD.EMAIL,
        SCD.CITY,
        SCD.STATE,
        SCD.COUNTRY
    FROM VAULT.HUB_CUSTOMER HC
    JOIN VAULT.SAT_CUSTOMER_DETAILS SCD
        ON HC.CUSTOMER_HK = SCD.CUSTOMER_HK
    WHERE SCD.ACTIVE_IND='Y'
) S
ON T.CUSTOMER_ID = S.CUSTOMER_ID

WHEN MATCHED
AND
(
       NVL(T.CUSTOMER_NAME,'') <> NVL(S.CUSTOMER_NAME,'')
    OR NVL(T.EMAIL,'')         <> NVL(S.EMAIL,'')
    OR NVL(T.CITY,'')          <> NVL(S.CITY,'')
    OR NVL(T.STATE,'')         <> NVL(S.STATE,'')
    OR NVL(T.COUNTRY,'')       <> NVL(S.COUNTRY,'')
)
THEN UPDATE SET
    CUSTOMER_NAME = S.CUSTOMER_NAME,
    EMAIL         = S.EMAIL,
    CITY          = S.CITY,
    STATE         = S.STATE,
    COUNTRY       = S.COUNTRY,
    UPDATED_TS    = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN
INSERT
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    EMAIL,
    CITY,
    STATE,
    COUNTRY,
    LOAD_DATE,
    CREATED_TS,
    UPDATED_TS
)
VALUES
(
    S.CUSTOMER_ID,
    S.CUSTOMER_NAME,
    S.EMAIL,
    S.CITY,
    S.STATE,
    S.COUNTRY,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
);




MERGE INTO DATA_MART.DIM_PRODUCT T
USING
(
    SELECT
        HC.PRODUCT_ID,
        SCD.PRODUCT_NAME,
        SCD.CATEGORY,
        SCD.BRAND
    FROM VAULT.HUB_PRODUCT HC
    JOIN VAULT.SAT_PRODUCT_DETAILS SCD
        ON HC.PRODUCT_HK = SCD.PRODUCT_HK
    WHERE SCD.ACTIVE_IND='Y'
) S
ON T.PRODUCT_ID = S.PRODUCT_ID

WHEN MATCHED
AND
(
       NVL(T.PRODUCT_NAME,'') <> NVL(S.PRODUCT_NAME,'')
    OR NVL(T.CATEGORY,'')         <> NVL(S.CATEGORY,'')
    OR NVL(T.BRAND,'')          <> NVL(S.BRAND,'')
)
THEN UPDATE SET
    PRODUCT_NAME = S.PRODUCT_NAME,
    CATEGORY         = S.CATEGORY,
    BRAND          = S.BRAND,
    UPDATED_TS    = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN
INSERT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    BRAND,
    LOAD_DATE,
    CREATED_TS,
    UPDATED_TS
)
VALUES
(
    S.PRODUCT_ID,
    S.PRODUCT_NAME,
    S.CATEGORY,
    S.BRAND,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
);




MERGE INTO DATA_MART.DIM_SELLER T
USING
(
    SELECT
        HC.SELLER_ID,
        SCD.SELLER_NAME,
        SCD.SELLER_RATING,
        SCD.CITY,
		SCD.COUNTRY,
    FROM VAULT.HUB_SELLER HC
    JOIN VAULT.SAT_SELLER_DETAILS SCD
        ON HC.SELLER_HK = SCD.SELLER_HK
    WHERE SCD.ACTIVE_IND='Y'
) S
ON T.SELLER_ID = S.SELLER_ID

WHEN MATCHED
AND
(
       NVL(T.SELLER_NAME,'') <> NVL(S.SELLER_NAME,'')
    OR NVL(T.SELLER_RATING,'')         <> NVL(S.SELLER_RATING,'')
    OR NVL(T.CITY,'')          <> NVL(S.CITY,'')
	OR NVL(T.COUNTRY,'')          <> NVL(S.COUNTRY,'')
)
THEN UPDATE SET
    SELLER_NAME = S.SELLER_NAME,
    SELLER_RATING         = S.SELLER_RATING,
    CITY          = S.CITY,
    COUNTRY          = S.COUNTRY,
    UPDATED_TS    = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN
INSERT
(
    SELLER_ID,
    SELLER_NAME,
    SELLER_RATING,
    CITY,
	COUNTRY,
    LOAD_DATE,
    CREATED_TS,
    UPDATED_TS
)
VALUES
(
    S.SELLER_ID,
    S.SELLER_NAME,
    S.SELLER_RATING,
    S.CITY,
	S.COUNTRY,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
);




INSERT INTO DIM_DATE
(
    DATE_KEY,
    FULL_DATE,
    DAY_NUMBER,
    MONTH_NUMBER,
    MONTH_NAME,
    QUARTER_NUMBER,
    YEAR_NUMBER
)
SELECT
    TO_NUMBER(TO_CHAR(DATE_VALUE,'YYYYMMDD')) AS DATE_KEY,
    DATE_VALUE AS FULL_DATE,
    DAY(DATE_VALUE) AS DAY_NUMBER,
    MONTH(DATE_VALUE) AS MONTH_NUMBER,
    MONTHNAME(DATE_VALUE) AS MONTH_NAME,
    QUARTER(DATE_VALUE) AS QUARTER_NUMBER,
    YEAR(DATE_VALUE) AS YEAR_NUMBER
FROM
(
    SELECT
        DATEADD(
            DAY,
            SEQ4(),
            '2020-01-01'
        ) AS DATE_VALUE
    FROM TABLE(GENERATOR(ROWCOUNT => 3650))
);




