USE SCHEMA VAULT;


CREATE OR REPLACE TASK DATA_VAULT_HUB_TASK
WAREHOUSE = LEARNING_WH
SCHEDULE = '5 MINUTE'
AS
CALL SP_LOAD_DATA_VAULT_HUBS();

ALTER TASK DATA_VAULT_HUB_TASK SUSPEND;
ALTER TASK DATA_VAULT_HUB_TASK RESUME;


CREATE OR REPLACE TASK DATA_VAULT_LINK_TASK
WAREHOUSE = LEARNING_WH
SCHEDULE = '5 MINUTE'
AS
CALL SP_LOAD_DATA_VAULT_LINKS();

ALTER TASK DATA_VAULT_LINK_TASK SUSPEND;
ALTER TASK DATA_VAULT_LINK_TASK RESUME;


CREATE OR REPLACE TASK DATA_VAULT_SAT_TASK
WAREHOUSE = LEARNING_WH
SCHEDULE = '5 MINUTE'
AS
CALL SP_LOAD_DATA_VAULT_SAT();

ALTER TASK DATA_VAULT_SAT_TASK SUSPEND;
ALTER TASK DATA_VAULT_SAT_TASK RESUME;