CREATE OR REPLACE PROCEDURE SP_LOAD_DATA_VAULT_HUBS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
insert into VAULT.hub_customer 
(CUSTOMER_HK,
    CUSTOMER_ID,
    LOAD_DATE,
    RECORD_SOURCE )
    SELECT
    MD5(UPPER(TRIM(CUSTOMER_ID))) AS CUSTOMER_HK,
    CUSTOMER_ID,
    CURRENT_TIMESTAMP(),
    'CRM_SYSTEM'
FROM STAGE_DEV.STG_CUSTOMERS;




insert into VAULT.HUB_PRODUCT 
(PRODUCT_HK,
    PRODUCT_ID,
    LOAD_DATE,
    RECORD_SOURCE )
    SELECT
    MD5(UPPER(TRIM(PRODUCT_ID))) AS PRODUCt_HK,
    PRODUCT_ID,
    CURRENT_TIMESTAMP(),
    'CRM_SYSTEM'
FROM STAGE_DEV.STG_PRODUCTs;


insert into VAULT.HUB_ORDER 
(ORDER_HK,
    ORDER_ID,
    LOAD_DATE,
    RECORD_SOURCE )
    SELECT
    MD5(UPPER(TRIM(ORDER_ID))) AS ORDER_HK,
    ORDER_ID,
    CURRENT_TIMESTAMP(),
    'CRM_SYSTEM'
FROM STAGE_DEV.STG_ORDERs;



insert into VAULT.HUB_SELLER 
(SELLER_HK,
    SELLER_ID,
    LOAD_DATE,
    RECORD_SOURCE )
    SELECT
    MD5(UPPER(TRIM(SELLER_ID))) AS SELLER_HK,
    SELLER_ID,
    CURRENT_TIMESTAMP(),
    'CRM_SYSTEM'
FROM STAGE_DEV.STG_SELLERS;



insert into VAULT.HUB_PROMOTION
(PROMOTION_HK,
    PROMOTION_ID,
    LOAD_DATE,
    RECORD_SOURCE )
    SELECT
    MD5(UPPER(TRIM(PROMOTION_ID))) AS PROMOTION_HK,
    PROMOTION_ID,
    CURRENT_TIMESTAMP(),
    'CRM_SYSTEM'
FROM STAGE_DEV.STG_PROMOTIONs;
 RETURN 'SUCCESS';

END;
$$;



INSERT INTO LINK_CUSTOMER_ORDER (
    CUSTOMER_ORDER_HK,
    CUSTOMER_HK,
    ORDER_HK,
    LOAD_DATE,
    RECORD_SOURCE
)
SELECT
    MD5(HP.CUSTOMER_HK || '|' || HO.ORDER_HK),
 HP.CUSTOMER_HK,
    HO.ORDER_HK,

    CURRENT_TIMESTAMP(),
    'ORDER_SYSTEM'

FROM (
    SELECT DISTINCT
        ORDER_ID,
        CUSTOMER_ID
    FROM STAGE_DEV.STG_ORDERS
    WHERE ORDER_ID IS NOT NULL
      AND CUSTOMER_ID IS NOT NULL
) S

JOIN HUB_ORDER HO
    ON HO.ORDER_HK = MD5(UPPER(TRIM(S.ORDER_ID)))

JOIN HUB_CUSTOMER HP
    ON HP.CUSTOMER_HK = MD5(UPPER(TRIM(S.CUSTOMER_ID)))

WHERE NOT EXISTS (
    SELECT 1
    FROM LINK_CUSTOMER_ORDER L
    WHERE L.CUSTOMER_ORDER_HK =
           MD5(HP.CUSTOMER_HK || '|' || HO.ORDER_HK)
);




INSERT INTO LINK_PRODUCT_SELLER (
    PRODUCT_SELLER_HK,
    PRODUCT_HK,
    SELLER_HK,
    LOAD_DATE,
    RECORD_SOURCE
)
SELECT
    MD5(HO.PRODUCT_HK || '|' || HP.SELLER_HK),
 HO.PRODUCT_HK,
    HP.SELLER_HK,

    CURRENT_TIMESTAMP(),
    'ORDER_SYSTEM'

FROM (
    SELECT DISTINCT
        PRODUCT_ID,
        SELLER_ID              
    FROM STAGE_DEV.STG_ORDER_ITEMS
    WHERE PRODUCT_ID IS NOT NULL
      AND PRODUCT_ID IS NOT NULL
) S

JOIN HUB_PRODUCT HO
    ON HO.PRODUCT_HK = MD5(UPPER(TRIM(S.PRODUCT_ID)))

JOIN HUB_SELLER HP
    ON HP.SELLER_hk = MD5(UPPER(TRIM(S.SELLER_ID)))

WHERE NOT EXISTS (
    SELECT 1
    FROM LINK_PRODUCT_SELLER L
    WHERE L.PRODUCT_SELLER_HK =
          MD5(HO.PRODUCT_HK || '|' || HP.SELLER_HK)
);




INSERT INTO LINK_PRODUCT_PROMOTION (
    PRODUCT_PROMOTION_HK,
    PRODUCT_HK,
    PROMOTION_HK,
    LOAD_DATE,
    RECORD_SOURCE
)
SELECT
    MD5(HO.PRODUCT_HK || '|' || HP.PROMOTION_HK),
 HO.PRODUCT_HK,
    HP.PROMOTION_HK,

    CURRENT_TIMESTAMP(),
    'ORDER_SYSTEM'

FROM (
    SELECT DISTINCT
        PRODUCT_ID,
        PROMOTION_ID              
    FROM STAGE_DEV.STG_PROMOTIONS
    WHERE PRODUCT_ID IS NOT NULL
      AND PROMOTION_ID IS NOT NULL
) S

JOIN HUB_PRODUCT HO
    ON HO.PRODUCT_HK = MD5(UPPER(TRIM(S.PRODUCT_ID)))

JOIN HUB_PROMOTION HP
    ON HP.PROMOTION_HK = MD5(UPPER(TRIM(S.PROMOTION_ID)))

WHERE NOT EXISTS (
    SELECT 1
    FROM LINK_PRODUCT_PROMOTION L
    WHERE L.PRODUCT_PROMOTION_HK =
          MD5(HO.PRODUCT_HK || '|' || HP.PROMOTION_HK)
);




INSERT INTO LINK_ORDER_PRODUCT (
    ORDER_PRODUCT_HK,
	 ORDER_HK,
    PRODUCT_HK,
    LOAD_DATE,
    RECORD_SOURCE
)
SELECT
    MD5(HO.PRODUCT_HK || '|' || HP.ORDER_HK),
 HO.PRODUCT_HK,
    HP.ORDER_HK,

    CURRENT_TIMESTAMP(),
    'ORDER_SYSTEM'

FROM (
    SELECT DISTINCT
        PRODUCT_ID,
        ORDER_ID              
    FROM STAGE_DEV.STG_ORDER_ITEMS
    WHERE PRODUCT_ID IS NOT NULL
      AND ORDER_ID IS NOT NULL
) S

JOIN HUB_PRODUCT HO
    ON HO.PRODUCT_HK = MD5(UPPER(TRIM(S.PRODUCT_ID)))

JOIN HUB_ORDER HP
    ON HP.ORDER_HK = MD5(UPPER(TRIM(S.ORDER_ID)))

WHERE NOT EXISTS (
    SELECT 1
    FROM LINK_ORDER_PRODUCT L
    WHERE L.ORDER_PRODUCT_HK =
          MD5(HO.PRODUCT_HK || '|' || HP.ORDER_HK)
);



INSERT INTO LINK_ORDER_PROMOTION (
    ORDER_PROMOTION_HK,
	 ORDER_HK,
    PROMOTION_HK,
    LOAD_DATE,
    RECORD_SOURCE
)
SELECT
    MD5(HO.PROMOTION_HK || '|' || HP.ORDER_HK),
 HO.PROMOTION_HK,
    HP.ORDER_HK,

    CURRENT_TIMESTAMP(),
    'ORDER_SYSTEM'

FROM (
    SELECT DISTINCT
        PROMOTION_ID,
        SOT.ORDER_ID              
    FROM STAGE_DEV.STG_PROMOTIONS SP
	left join STAGE_DEV.STG_ORDER_ITEMS SOT on SP.PRODUCT_ID=SOT.PRODUCT_ID
    WHERE PROMOTION_ID IS NOT NULL
      AND ORDER_ID IS NOT NULL
) S

JOIN HUB_PROMOTION HO
    ON HO.PROMOTION_HK = MD5(UPPER(TRIM(S.PROMOTION_ID)))

JOIN HUB_ORDER HP
    ON HP.ORDER_HK = MD5(UPPER(TRIM(S.ORDER_ID)))

WHERE NOT EXISTS (
    SELECT 1
    FROM LINK_ORDER_PROMOTION L
    WHERE L.ORDER_PROMOTION_HK =
          MD5(HO.PROMOTION_HK || '|' || HP.ORDER_HK)
);



MERGE INTO SAT_CUSTOMER_DETAILS T 
USING 
(select
MD5(UPPER(TRIM(CUSTOMER_ID))) AS CUSTOMER_HK,
    CUSTOMER_NAME,
    EMAIL,
    CITY,
     MD5(
            UPPER(TRIM(COALESCE(CUSTOMER_NAME,''))) || '|' ||
             UPPER(TRIM(COALESCE(phone,''))) || '|' ||
            UPPER(TRIM(COALESCE(EMAIL,''))) || '|' ||
            UPPER(TRIM(COALESCE(CITY,''))) || '|' ||
            UPPER(TRIM(COALESCE(STATE,''))) || '|' ||
            UPPER(TRIM(COALESCE(COUNTRY,''))) || '|' ||
            UPPER(TRIM(COALESCE(CUSTOMER_STATUS,''))) 
        )
 AS HASHDIFF from 
STAGE_DEV.STG_CUSTOMERS) S
ON T.CUSTOMER_HK = S.CUSTOMER_HK
AND T.ACTIVE_IND = 'Y'
WHEN MATCHED
AND T.HASHDIFF <> S.HASHDIFF

THEN UPDATE SET
    T.ACTIVE_IND = 'N';




INSERT INTO SAT_CUSTOMER_DETAILS (
    CUSTOMER_HK,
    CUSTOMER_NAME,
    EMAIL,
    PHONE,
    CITY,
    STATE,
    COUNTRY,
    CUSTOMER_STATUS,
    HASHDIFF,
    ACTIVE_IND,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    LOAD_DATE,
    RECORD_SOURCE
)

SELECT
    S.CUSTOMER_HK,
    S.CUSTOMER_NAME,
    S.EMAIL,
    S.PHONE,
    S.CITY,
    S.STATE,
    S.COUNTRY,
    S.CUSTOMER_STATUS,
    S.HASHDIFF,

    'Y' AS ACTIVE_IND,

    CURRENT_TIMESTAMP() AS EFFECTIVE_FROM,

    NULL AS EFFECTIVE_TO,

    CURRENT_TIMESTAMP() AS LOAD_DATE,

    'CRM' AS RECORD_SOURCE

FROM (

    SELECT
        MD5(UPPER(TRIM(CUSTOMER_ID))) AS CUSTOMER_HK,

        CUSTOMER_NAME,
        EMAIL,
        PHONE,
        CITY,
        STATE,
        COUNTRY,
        CUSTOMER_STATUS,

        MD5(
            UPPER(TRIM(COALESCE(CUSTOMER_NAME,''))) || '|' ||
            UPPER(TRIM(COALESCE(PHONE,''))) || '|' ||
            UPPER(TRIM(COALESCE(EMAIL,''))) || '|' ||
            UPPER(TRIM(COALESCE(CITY,''))) || '|' ||
            UPPER(TRIM(COALESCE(STATE,''))) || '|' ||
            UPPER(TRIM(COALESCE(COUNTRY,''))) || '|' ||
            UPPER(TRIM(COALESCE(CUSTOMER_STATUS,'')))
        ) AS HASHDIFF

    FROM STAGE_DEV.STG_CUSTOMERS

) S

LEFT JOIN SAT_CUSTOMER_DETAILS T
    ON S.CUSTOMER_HK = T.CUSTOMER_HK
   AND T.ACTIVE_IND = 'Y'

WHERE
      T.CUSTOMER_HK IS NULL
   OR T.HASHDIFF <> S.HASHDIFF;



MERGE INTO SAT_PRODUCT_DETAILS T 
USING 
(select
MD5(UPPER(TRIM(PRODUCT_ID))) AS PRODUCT_HK,
    PRODUCT_NAME,
    CATEGORY,
    BRAND,
	PRODUCT_STATUS,
     MD5(
            UPPER(TRIM(COALESCE(PRODUCT_NAME,''))) || '|' ||
             UPPER(TRIM(COALESCE(CATEGORY,''))) || '|' ||
            UPPER(TRIM(COALESCE(BRAND,''))) || '|' ||
            UPPER(TRIM(COALESCE(PRODUCT_STATUS,'')))  
        )
AS HASHDIFF from 
STAGE_DEV.STG_PRODUCTS) S
ON T.PRODUCT_HK = S.PRODUCT_HK
AND T.ACTIVE_IND = 'Y'
WHEN MATCHED
AND T.HASHDIFF <> S.HASHDIFF

THEN UPDATE SET
    T.ACTIVE_IND = 'N';



  INSERT INTO SAT_PRODUCT_DETAILS (
    PRODUCT_HK,
    PRODUCT_NAME,
    CATEGORY,
    BRAND,
	PRODUCT_STATUS,
    HASHDIFF,
    ACTIVE_IND,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    LOAD_DATE,
    RECORD_SOURCE
)

SELECT
    S.PRODUCT_HK,
    S.PRODUCT_NAME,
    S.CATEGORY,
    S.BRAND,
	S.PRODUCT_STATUS,
    S.HASHDIFF,

    'Y' AS ACTIVE_IND,

    CURRENT_TIMESTAMP() AS EFFECTIVE_FROM,

    NULL AS EFFECTIVE_TO,

    CURRENT_TIMESTAMP() AS LOAD_DATE,

    'CRM' AS RECORD_SOURCE

FROM (

    SELECT
        MD5(UPPER(TRIM(PRODUCT_ID))) AS PRODUCT_HK,

         PRODUCT_NAME,
    CATEGORY,
    BRAND,
	
        PRODUCT_STATUS,

        MD5(
            UPPER(TRIM(COALESCE(PRODUCT_NAME,''))) || '|' ||
             UPPER(TRIM(COALESCE(CATEGORY,''))) || '|' ||
            UPPER(TRIM(COALESCE(BRAND,''))) || '|' ||
            UPPER(TRIM(COALESCE(PRODUCT_STATUS,'')))  
        )
AS HASHDIFF
    FROM STAGE_DEV.STG_PRODUCTS

) S

LEFT JOIN SAT_PRODUCT_DETAILS T
    ON S.PRODUCT_HK = T.PRODUCT_HK
   AND T.ACTIVE_IND = 'Y'

WHERE
      T.PRODUCT_HK IS NULL
   OR T.HASHDIFF <> S.HASHDIFF;




MERGE INTO SAT_ORDER_DETAILS T 
USING 
(select
MD5(UPPER(TRIM(ORDER_ID))) AS ORDER_HK,
    TOTAL_AMOUNT,
	ORDER_STATUS,
     MD5(
             UPPER(TRIM(COALESCE(TOTAL_AMOUNT,0))) || '|' ||
            UPPER(TRIM(COALESCE(ORDER_STATUS,'')))  
        )
AS HASHDIFF from 
STAGE_DEV.STG_ORDERS) S
ON T.ORDER_HK = S.ORDER_HK
AND T.ACTIVE_IND = 'Y'
WHEN MATCHED
AND T.HASHDIFF <> S.HASHDIFF

THEN UPDATE SET
    T.ACTIVE_IND = 'N';




    INSERT INTO SAT_order_DETAILS (
    ORDER_HK,
    ORDER_STATUS,
	TOTAL_AMOUNT,
    HASHDIFF,
    ACTIVE_IND,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    LOAD_DATE,
    RECORD_SOURCE
)

SELECT
    S.ORDER_HK,
    S.ORDER_STATUS,
	S.TOTAL_AMOUNT,
    S.HASHDIFF,

    'Y' AS ACTIVE_IND,

    CURRENT_TIMESTAMP() AS EFFECTIVE_FROM,

    NULL AS EFFECTIVE_TO,

    CURRENT_TIMESTAMP() AS LOAD_DATE,

    'CRM' AS RECORD_SOURCE

FROM (

    SELECT
        MD5(UPPER(TRIM(ORDER_ID))) AS ORDER_HK,
        ORDER_STATUS,
		TOTAL_AMOUNT,

        MD5(
            UPPER(TRIM(COALESCE(TOTAL_AMOUNT,0))) || '|' ||
            UPPER(TRIM(COALESCE(ORDER_STATUS,'')))
        ) AS HASHDIFF

    FROM STAGE_DEV.STG_ORDERS

) S

LEFT JOIN SAT_ORDER_DETAILS T
    ON S.ORDER_HK = T.ORDER_HK
   AND T.ACTIVE_IND = 'Y'

WHERE
      T.ORDER_HK IS NULL
   OR T.HASHDIFF <> S.HASHDIFF;




INSERT INTO SAT_PROMOTION_DETAILS (
    PROMOTION_HK,
    PROMOTION_NAME,
	DISCOUNT_PERCENT,
    START_DATE             ,
	END_DATE  ,
    HASHDIFF,
    ACTIVE_IND,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    LOAD_DATE,
    RECORD_SOURCE
)

SELECT
    S.PROMOTION_HK,
    S.PROMOTION_NAME,
    S.DISCOUNT_PERCENT,
    S.START_DATE             ,
	S.END_DATE  ,
    S.HASHDIFF,

    'Y' AS ACTIVE_IND,

    CURRENT_TIMESTAMP() AS EFFECTIVE_FROM,

    NULL AS EFFECTIVE_TO,

    CURRENT_TIMESTAMP() AS LOAD_DATE,

    'CRM' AS RECORD_SOURCE

FROM (

    SELECT
        MD5(UPPER(TRIM(PROMOTION_ID))) AS PROMOTION_HK,

         PROMOTION_NAME,
    DISCOUNT_PERCENT,
    START_DATE             ,
	END_DATE             ,
     MD5(
            UPPER(TRIM(COALESCE(PROMOTION_NAME,''))) || '|' ||
             UPPER(TRIM(COALESCE(DISCOUNT_PERCENT,''))) || '|' ||
            UPPER(TRIM(COALESCE(START_DATE,''))) || '|' ||
            UPPER(TRIM(COALESCE(END_DATE,'')))  
        )
AS HASHDIFF
    FROM STAGE_DEV.STG_PROMOTIONS

) S

LEFT JOIN SAT_PROMOTION_DETAILS T
    ON S.PROMOTION_HK = T.PROMOTION_HK
   AND T.ACTIVE_IND = 'Y'

WHERE
      T.PROMOTION_HK IS NULL
   OR T.HASHDIFF <> S.HASHDIFF;     




MERGE INTO SAT_SELLER_DETAILS T 
USING 
(select
MD5(UPPER(TRIM(SELLER_ID))) AS SELLER_HK,
     SELLER_RATING,
	CITY,
    COUNTRY,
     MD5(
             UPPER(TRIM(COALESCE(SELLER_RATING,0))) || '|' ||
           
            UPPER(TRIM(COALESCE(CITY,'')))  || '|' ||
            UPPER(TRIM(COALESCE(COUNTRY,''))) 
			
        )
AS HASHDIFF from 
STAGE_DEV.STG_SELLERS) S
ON T.SELLER_HK = S.SELLER_HK
AND T.ACTIVE_IND = 'Y'
WHEN MATCHED
AND T.HASHDIFF <> S.HASHDIFF

THEN UPDATE SET
    T.ACTIVE_IND = 'N';




    INSERT INTO SAT_SELLER_DETAILS (
    SELLER_HK,
    SELLER_NAME,
	CITY,
    COUNTRY,
    HASHDIFF,
    ACTIVE_IND,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    LOAD_DATE,
    RECORD_SOURCE
)

SELECT
    S.SELLER_HK,
    S.SELLER_NAME,
    S.CITY,
    S.COUNTRY,
    S.HASHDIFF,

    'Y' AS ACTIVE_IND,

    CURRENT_TIMESTAMP() AS EFFECTIVE_FROM,

    NULL AS EFFECTIVE_TO,

    CURRENT_TIMESTAMP() AS LOAD_DATE,

    'CRM' AS RECORD_SOURCE

FROM (

    SELECT
        MD5(UPPER(TRIM(SELLER_ID))) AS SELLER_HK,
		SELLER_NAME,
        SELLER_RATING,
	CITY,
    COUNTRY,
     MD5(
             UPPER(TRIM(COALESCE(SELLER_NAME,''))) || '|' ||
	 
             UPPER(TRIM(COALESCE(SELLER_RATING,0))) || '|' ||
           
            UPPER(TRIM(COALESCE(CITY,'')))  || '|' ||
            UPPER(TRIM(COALESCE(COUNTRY,''))) 
			
        )
AS HASHDIFF
    FROM STAGE_DEV.STG_SELLERS

) S

LEFT JOIN SAT_SELLER_DETAILS T
    ON S.SELLER_HK = T.SELLER_HK
   AND T.ACTIVE_IND = 'Y'

WHERE
      T.SELLER_HK IS NULL
   OR T.HASHDIFF <> S.HASHDIFF;     




MERGE INTO SAT_PRODUCT_PRICE_HISTORY T 
USING 
(select
MD5(UPPER(TRIM(OT.SELLER_ID))) AS SELLER_HK,
MD5(UPPER(TRIM(PU.PRODUCT_ID))) AS PRODUCT_HK,

     PRICE,
    DISCOUNT_PERCENT       ,
	FINAL_PRICE            ,
     MD5(
             UPPER(TRIM(COALESCE(PRICE,0))) || '|' ||
           
            UPPER(TRIM(COALESCE(DISCOUNT_PERCENT,'')))  || '|' ||
            UPPER(TRIM(COALESCE(FINAL_PRICE,''))) 
        )
AS HASHDIFF from 
STAGE_DEV.STG_PRICE_UPDATES PU
left join STAGE_DEV.STG_ORDER_ITEMS OT on PU.PRODUCT_ID=OT.PRODUCT_ID
) S
ON T.SELLER_HK = S.SELLER_HK
and T.PRODUCT_HK = S.PRODUCT_HK
AND T.ACTIVE_IND = 'Y'
WHEN MATCHED
AND T.HASHDIFF <> S.HASHDIFF

THEN UPDATE SET
    T.ACTIVE_IND = 'N';




INSERT INTO SAT_PRODUCT_PRICE_HISTORY (
PRODUCT_HK,
    SELLER_HK,
     PRICE,
    DISCOUNT_PERCENT       ,
	FINAL_PRICE            ,
    HASHDIFF,
    ACTIVE_IND,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    LOAD_DATE,
    RECORD_SOURCE
)

SELECT
    S.SELLER_HK,
	S.PRODUCT_HK,
     S.PRICE,
    S.DISCOUNT_PERCENT       ,
	S.FINAL_PRICE            ,
    S.HASHDIFF,

    'Y' AS ACTIVE_IND,

    CURRENT_TIMESTAMP() AS EFFECTIVE_FROM,

    NULL AS EFFECTIVE_TO,

    CURRENT_TIMESTAMP() AS LOAD_DATE,

    'CRM' AS RECORD_SOURCE

FROM (

    SELECT
        MD5(UPPER(TRIM(OT.SELLER_ID))) AS SELLER_HK,
		MD5(UPPER(TRIM(PU.PRODUCT_ID))) AS PRODUCT_HK,
		 PRICE,
    DISCOUNT_PERCENT       ,
	FINAL_PRICE            ,
     MD5(
             UPPER(TRIM(COALESCE(PRICE,0))) || '|' ||
           
            UPPER(TRIM(COALESCE(DISCOUNT_PERCENT,'')))  || '|' ||
            UPPER(TRIM(COALESCE(FINAL_PRICE,''))) 
        )
AS HASHDIFF
 from   STAGE_DEV.STG_PRICE_UPDATES PU
left join STAGE_DEV.STG_ORDER_ITEMS OT on PU.PRODUCT_ID=OT.PRODUCT_ID

) S

LEFT JOIN SAT_SELLER_DETAILS T
    ON S.SELLER_HK = T.SELLER_HK
   AND T.ACTIVE_IND = 'Y'

WHERE
      T.SELLER_HK IS NULL
   OR T.HASHDIFF <> S.HASHDIFF;     









