insert into VAULT.hub_customer 
(CUSTOMER_HK,
    CUSTOMER_ID,
    LOAD_DATE,
    RECORD_SOURCE )
    SELECT
    MD5(UPPER(TRIM(CUSTOMER_ID))) AS CUSTOMER_HK,
    CUSTOMER_ID,
    CURRENT_TIMESTAMP(),
    'CRM_SYSTEM'
FROM STAGE_DEV.STG_CUSTOMERS;




insert into VAULT.HUB_PRODUCT 
(PRODUCT_HK,
    PRODUCT_ID,
    LOAD_DATE,
    RECORD_SOURCE )
    SELECT
    MD5(UPPER(TRIM(PRODUCT_ID))) AS PRODUCt_HK,
    PRODUCT_ID,
    CURRENT_TIMESTAMP(),
    'CRM_SYSTEM'
FROM STAGE_DEV.STG_PRODUCTs;


insert into VAULT.HUB_ORDER 
(ORDER_HK,
    ORDER_ID,
    LOAD_DATE,
    RECORD_SOURCE )
    SELECT
    MD5(UPPER(TRIM(ORDER_ID))) AS ORDER_HK,
    ORDER_ID,
    CURRENT_TIMESTAMP(),
    'CRM_SYSTEM'
FROM STAGE_DEV.STG_ORDERs;



insert into VAULT.HUB_SELLER 
(SELLER_HK,
    SELLER_ID,
    LOAD_DATE,
    RECORD_SOURCE )
    SELECT
    MD5(UPPER(TRIM(SELLER_ID))) AS SELLER_HK,
    SELLER_ID,
    CURRENT_TIMESTAMP(),
    'CRM_SYSTEM'
FROM STAGE_DEV.STG_SELLERS;



insert into VAULT.HUB_PROMOTION
(PROMOTION_HK,
    PROMOTION_ID,
    LOAD_DATE,
    RECORD_SOURCE )
    SELECT
    MD5(UPPER(TRIM(PROMOTION_ID))) AS PROMOTION_HK,
    PROMOTION_ID,
    CURRENT_TIMESTAMP(),
    'CRM_SYSTEM'
FROM STAGE_DEV.STG_PROMOTIONs;




INSERT INTO LINK_CUSTOMER_ORDER (
    CUSTOMER_ORDER_HK,
    CUSTOMER_HK,
    ORDER_HK,
    LOAD_DATE,
    RECORD_SOURCE
)
SELECT
    MD5(HP.CUSTOMER_HK || '|' || HO.ORDER_HK),
 HP.CUSTOMER_HK,
    HO.ORDER_HK,

    CURRENT_TIMESTAMP(),
    'ORDER_SYSTEM'

FROM (
    SELECT DISTINCT
        ORDER_ID,
        CUSTOMER_ID
    FROM STAGE_DEV.STG_ORDERS
    WHERE ORDER_ID IS NOT NULL
      AND CUSTOMER_ID IS NOT NULL
) S

JOIN HUB_ORDER HO
    ON HO.ORDER_HK = MD5(UPPER(TRIM(S.ORDER_ID)))

JOIN HUB_CUSTOMER HP
    ON HP.CUSTOMER_HK = MD5(UPPER(TRIM(S.CUSTOMER_ID)))

WHERE NOT EXISTS (
    SELECT 1
    FROM LINK_CUSTOMER_ORDER L
    WHERE L.CUSTOMER_ORDER_HK =
           MD5(HP.CUSTOMER_HK || '|' || HO.ORDER_HK)
);




INSERT INTO LINK_PRODUCT_SELLER (
    PRODUCT_SELLER_HK,
    PRODUCT_HK,
    SELLER_HK,
    LOAD_DATE,
    RECORD_SOURCE
)
SELECT
    MD5(HO.PRODUCT_HK || '|' || HP.SELLER_HK),
 HO.PRODUCT_HK,
    HP.SELLER_HK,

    CURRENT_TIMESTAMP(),
    'ORDER_SYSTEM'

FROM (
    SELECT DISTINCT
        PRODUCT_ID,
        SELLER_ID              
    FROM STAGE_DEV.STG_ORDER_ITEMS
    WHERE PRODUCT_ID IS NOT NULL
      AND PRODUCT_ID IS NOT NULL
) S

JOIN HUB_PRODUCT HO
    ON HO.PRODUCT_HK = MD5(UPPER(TRIM(S.PRODUCT_ID)))

JOIN HUB_SELLER HP
    ON HP.SELLER_hk = MD5(UPPER(TRIM(S.SELLER_ID)))

WHERE NOT EXISTS (
    SELECT 1
    FROM LINK_PRODUCT_SELLER L
    WHERE L.PRODUCT_SELLER_HK =
          MD5(HO.PRODUCT_HK || '|' || HP.SELLER_HK)
);




INSERT INTO LINK_PRODUCT_PROMOTION (
    PRODUCT_PROMOTION_HK,
    PRODUCT_HK,
    PROMOTION_HK,
    LOAD_DATE,
    RECORD_SOURCE
)
SELECT
    MD5(HO.PRODUCT_HK || '|' || HP.PROMOTION_HK),
 HO.PRODUCT_HK,
    HP.PROMOTION_HK,

    CURRENT_TIMESTAMP(),
    'ORDER_SYSTEM'

FROM (
    SELECT DISTINCT
        PRODUCT_ID,
        PROMOTION_ID              
    FROM STAGE_DEV.STG_PROMOTIONS
    WHERE PRODUCT_ID IS NOT NULL
      AND PROMOTION_ID IS NOT NULL
) S

JOIN HUB_PRODUCT HO
    ON HO.PRODUCT_HK = MD5(UPPER(TRIM(S.PRODUCT_ID)))

JOIN HUB_PROMOTION HP
    ON HP.PROMOTION_HK = MD5(UPPER(TRIM(S.PROMOTION_ID)))

WHERE NOT EXISTS (
    SELECT 1
    FROM LINK_PRODUCT_PROMOTION L
    WHERE L.PRODUCT_PROMOTION_HK =
          MD5(HO.PRODUCT_HK || '|' || HP.PROMOTION_HK)
);




INSERT INTO LINK_ORDER_PRODUCT (
    ORDER_PRODUCT_HK,
	 ORDER_HK,
    PRODUCT_HK,
    LOAD_DATE,
    RECORD_SOURCE
)
SELECT
    MD5(HO.PRODUCT_HK || '|' || HP.ORDER_HK),
 HO.PRODUCT_HK,
    HP.ORDER_HK,

    CURRENT_TIMESTAMP(),
    'ORDER_SYSTEM'

FROM (
    SELECT DISTINCT
        PRODUCT_ID,
        ORDER_ID              
    FROM STAGE_DEV.STG_ORDER_ITEMS
    WHERE PRODUCT_ID IS NOT NULL
      AND ORDER_ID IS NOT NULL
) S

JOIN HUB_PRODUCT HO
    ON HO.PRODUCT_HK = MD5(UPPER(TRIM(S.PRODUCT_ID)))

JOIN HUB_ORDER HP
    ON HP.ORDER_HK = MD5(UPPER(TRIM(S.ORDER_ID)))

WHERE NOT EXISTS (
    SELECT 1
    FROM LINK_ORDER_PRODUCT L
    WHERE L.ORDER_PRODUCT_HK =
          MD5(HO.PRODUCT_HK || '|' || HP.ORDER_HK)
);



INSERT INTO LINK_ORDER_PROMOTION (
    ORDER_PROMOTION_HK,
	 ORDER_HK,
    PROMOTION_HK,
    LOAD_DATE,
    RECORD_SOURCE
)
SELECT
    MD5(HO.PROMOTION_HK || '|' || HP.ORDER_HK),
 HO.PROMOTION_HK,
    HP.ORDER_HK,

    CURRENT_TIMESTAMP(),
    'ORDER_SYSTEM'

FROM (
    SELECT DISTINCT
        PROMOTION_ID,
        SOT.ORDER_ID              
    FROM STAGE_DEV.STG_PROMOTIONS SP
	left join STAGE_DEV.STG_ORDER_ITEMS SOT on SP.PRODUCT_ID=SOT.PRODUCT_ID
    WHERE PROMOTION_ID IS NOT NULL
      AND ORDER_ID IS NOT NULL
) S

JOIN HUB_PROMOTION HO
    ON HO.PROMOTION_HK = MD5(UPPER(TRIM(S.PROMOTION_ID)))

JOIN HUB_ORDER HP
    ON HP.ORDER_HK = MD5(UPPER(TRIM(S.ORDER_ID)))

WHERE NOT EXISTS (
    SELECT 1
    FROM LINK_ORDER_PROMOTION L
    WHERE L.ORDER_PROMOTION_HK =
          MD5(HO.PROMOTION_HK || '|' || HP.ORDER_HK)
);



