CREATE ROLE POWERBI_ROLE;
GRANT USAGE ON WAREHOUSE LEARNING_WH TO ROLE POWERBI_ROLE;
GRANT USAGE ON DATABASE DEVELOPMENT TO ROLE POWERBI_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DEVELOPMENT TO ROLE POWERBI_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE DEVELOPMENT TO ROLE POWERBI_ROLE;

CREATE USER POWERBI_USER
PASSWORD = 'StrongPassword123!'
DEFAULT_ROLE = POWERBI_ROLE
DEFAULT_WAREHOUSE = LEARNING_WH;
GRANT ROLE POWERBI_ROLE TO USER POWERBI_USER;